trigger:
  batch: true
  branches:
    include:
    - 'master'
    - 'main'

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

pool:
  vmImage: ubuntu-latest

variables:
- name: buildConfiguration
  value: 'Release'
- name: Version
  value: 1.0.$(Build.BuildId)

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'aeaa4311-673f-4791-a14d-d19ad82f0603'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '**/Ledgerscope.CodeGen.Decorators.csproj'
      versioningScheme: 'byBuildNumber'
      arguments: '--configuration $(BuildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: Publish 'drop' artifacts
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop
  
  - task: DotNetCoreCLI@2
    displayName: 'Push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'aeaa4311-673f-4791-a14d-d19ad82f0603'